In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("CGMData.csv")
df.head()

/tmp/ipykernel_243805/1796423919.py:1: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("CGMData.csv")

,Index,Date,Time,New Device Time,BG Reading (mg/dL),Linked BG Meter ID,Basal Rate (U/h),Temp Basal Amount,Temp Basal Type,Temp Basal Duration (h:mm:ss),...,Scroll Step Size,Insulin Action Curve Time,Sensor Calibration Rejected Reason,Preset Bolus,Bolus Source,Network Device Associated Reason,Network Device Disassociated Reason,Network Device Disconnected Reason,Sensor Exception,Preset Temp Basal Name
0,20355,2/12/2018,13:22:27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20356,2/12/2018,13:17:27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20357,2/12/2018,13:12:27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SENSOR_ERROR,NaN
3,20358,2/12/2018,13:07:27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SENSOR_ERROR,NaN
4,20359,2/12/2018,13:02:27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SENSOR_ERROR,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55343 entries, 0 to 55342
Data columns (total 47 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Index                                55343 non-null  int64
 1   Date                                 55343 non-null  object
 2   Time                                 55343 non-null  object
 3   New Device Time                      0 non-null      float64
 4   BG Reading (mg/dL)                   0 non-null      float64
 5   Linked BG Meter ID                   0 non-null      float64
 6   Basal Rate (U/h)                     0 non-null      float64
 7   Temp Basal Amount                    0 non-null      float64
 8   Temp Basal Type                      0 non-null      float64
 9   Temp Basal Duration (h:mm:ss)        0 non-null      float64
 10  Bolus Type                           0 non-null      float64
 11  Bolus Volume Selected (U)            0 non-null      float64
 12  Bolus Volume Delivered (U)           0 non-null      float64
 13  Bolus Duration (h:mm:ss)             0 non-null      float64
 14  Prime Type                           0 non-null      float64
 15  Prime Volume Delivered (U)           0 non-null      float64
 16  Alarm                                0 non-null      float64
 17  Suspend                              0 non-null      float64
 18  Rewind                               0 non-null      float64
 19  BWZ Estimate (U)                     0 non-null      float64
 20  BWZ Target High BG (mg/dL)           0 non-null      float64
 21  BWZ Target Low BG (mg/dL)            0 non-null      float64
 22  BWZ Carb Ratio (g/U)                 0 non-null      float64
 23  BWZ Insulin Sensitivity (mg/dL/U)    0 non-null      float64
 24  BWZ Carb Input (grams)               0 non-null      float64
 25  BWZ BG Input (mg/dL)                 0 non-null      float64
 26  BWZ Correction Estimate (U)          0 non-null      float64
 27  BWZ Food Estimate (U)                0 non-null      float64
 28  BWZ Active Insulin (U)               0 non-null      float64
 29  Sensor Calibration BG (mg/dL)        0 non-null      float64
 30  Sensor Glucose (mg/dL)               51175 non-null  float64
 31  ISIG Value                           51175 non-null  float64
 32  Event Marker                         1 non-null      object
 33  Bolus Number                         0 non-null      float64
 34  Bolus Cancellation Reason            0 non-null      float64
 35  BWZ Unabsorbed Insulin Total (U)     0 non-null      float64
 36  Final Bolus Estimate                 0 non-null      float64
 37  Scroll Step Size                     0 non-null      float64
 38  Insulin Action Curve Time            0 non-null      float64
 39  Sensor Calibration Rejected Reason   0 non-null      float64
 40  Preset Bolus                         0 non-null      float64
 41  Bolus Source                         0 non-null      float64
 42  Network Device Associated Reason     0 non-null      float64
 43  Network Device Disassociated Reason  0 non-null      float64
 44  Network Device Disconnected Reason   0 non-null      float64
 45  Sensor Exception                     4167 non-null   object
 46  Preset Temp Basal Name               0 non-null      float64
dtypes: float64(42), int64(1), object(4)
memory usage: 19.8+ MB

In [4]:
df1 = pd.read_csv("InsulinData.csv")
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41435 entries, 0 to 41434
Data columns (total 47 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Index                                41435 non-null  int64
 1   Date                                 41435 non-null  object
 2   Time                                 41435 non-null  object
 3   New Device Time                      8 non-null      object
 4   BG Reading (mg/dL)                   3737 non-null   float64
 5   Linked BG Meter ID                   0 non-null      float64
 6   Basal Rate (U/h)                     2022 non-null   float64
 7   Temp Basal Amount                    0 non-null      float64
 8   Temp Basal Type                      0 non-null      float64
 9   Temp Basal Duration (h:mm:ss)        0 non-null      float64
 10  Bolus Type                           29501 non-null  object
 11  Bolus Volume Selected (U)            29457 non-null  float64
 12  Bolus Volume Delivered (U)           28486 non-null  float64
 13  Bolus Duration (h:mm:ss)             7 non-null      object
 14  Prime Type                           120 non-null    object
 15  Prime Volume Delivered (U)           120 non-null    float64
 16  Alarm                                3535 non-null   object
 17  Suspend                              512 non-null    object
 18  Rewind                               56 non-null     object
 19  BWZ Estimate (U)                     1040 non-null   float64
 20  BWZ Target High BG (mg/dL)           163 non-null    float64
 21  BWZ Target Low BG (mg/dL)            163 non-null    float64
 22  BWZ Carb Ratio (g/U)                 1040 non-null   float64
 23  BWZ Insulin Sensitivity (mg/dL/U)    163 non-null    float64
 24  BWZ Carb Input (grams)               1040 non-null   float64
 25  BWZ BG Input (mg/dL)                 1040 non-null   float64
 26  BWZ Correction Estimate (U)          1040 non-null   float64
 27  BWZ Food Estimate (U)                1040 non-null   float64
 28  BWZ Active Insulin (U)               163 non-null    float64
 29  Sensor Calibration BG (mg/dL)        620 non-null    float64
 30  Sensor Glucose (mg/dL)               0 non-null      float64
 31  ISIG Value                           0 non-null      float64
 32  Event Marker                         0 non-null      float64
 33  Bolus Number                         29501 non-null  float64
 34  Bolus Cancellation Reason            44 non-null     object
 35  BWZ Unabsorbed Insulin Total (U)     163 non-null    float64
 36  Final Bolus Estimate                 163 non-null    float64
 37  Scroll Step Size                     163 non-null    object
 38  Insulin Action Curve Time            46 non-null     float64
 39  Sensor Calibration Rejected Reason   29 non-null     object
 40  Preset Bolus                         0 non-null      float64
 41  Bolus Source                         29457 non-null  object
 42  Network Device Associated Reason     5 non-null      object
 43  Network Device Disassociated Reason  2 non-null      object
 44  Network Device Disconnected Reason   39 non-null     object
 45  Sensor Exception                     0 non-null      float64
 46  Preset Temp Basal Name               0 non-null      float64
dtypes: float64(30), int64(1), object(16)
memory usage: 14.9+ MB

/tmp/ipykernel_243805/1196546665.py:1: DtypeWarning: Columns (13,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("InsulinData.csv")

In [5]:
df1.head()

,Index,Date,Time,New Device Time,BG Reading (mg/dL),Linked BG Meter ID,Basal Rate (U/h),Temp Basal Amount,Temp Basal Type,Temp Basal Duration (h:mm:ss),...,Scroll Step Size,Insulin Action Curve Time,Sensor Calibration Rejected Reason,Preset Bolus,Bolus Source,Network Device Associated Reason,Network Device Disassociated Reason,Network Device Disconnected Reason,Sensor Exception,Preset Temp Basal Name
0,0,2/12/2018,13:20:53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,TEMPORARY,NaN,NaN,NaN,NaN
1,1,2/12/2018,13:20:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2/12/2018,13:18:48,NaN,NaN,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2/12/2018,13:18:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2/12/2018,13:12:33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,CLOSED_LOOP_MICRO_BOLUS,NaN,NaN,NaN,NaN,NaN

In [6]:
df[['Date', 'Time', 'New Device Time']].head()

        Date      Time  New Device Time
0  2/12/2018  13:22:27              NaN
1  2/12/2018  13:17:27              NaN
2  2/12/2018  13:12:27              NaN
3  2/12/2018  13:07:27              NaN
4  2/12/2018  13:02:27              NaN

In [7]:
for col in df1.columns:
    if df1[col].dtype == object or df1[col].dtype == 'O':
        # Look for the string in that column
        if df1[col].str.contains("AUTO MODE ACTIVE PLGM OFF", na=False).any():
            print(f"Found auto-mode text in column: {col}")

Found auto-mode text in column: Alarm